name: sign_in_with_apple_js_example
description: "An example `webdev serve` app using the `sign_in_with_apple_js` interop package"
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sign_in_with_apple_js:
    path: ../

dev_dependencies:
  pedantic: ^1.11.0
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=2.12.0 <3.0.0'