name: sign_in_with_apple_js
description: "A Dart wrapper for the 'Sign in with Apple JS' framework with helper methods to simplify usage."
version: 2.0.1
homepage: https://github.com/mhrst/sign_in_with_apple_js
repository: https://github.com/mhrst/sign_in_with_apple_js
issue_tracker: https://github.com/mhrst/sign_in_with_apple_js/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  pedantic: ^1.11.0